version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_DB: suprema
      POSTGRES_USER: quarkususer
      POSTGRES_PASSWORD: quarkuspassword
    ports:
      - "5432:5432"
    networks:
      - quarkus-network

  # Service Quarkus
  quarkus:
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    container_name: quarkus-container
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgres
      QUARKUS_DATASOURCE_USERNAME: quarkususer
      QUARKUS_DATASOURCE_PASSWORD: quarkuspassword
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/suprema
    ports:
      - "8080:8080"
    networks:
      - quarkus-network

networks:
  quarkus-network:
    driver: bridge
